# Generated by Django 3.1.14 on 2023-11-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrystalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crystal_formula', models.CharField(blank=True, max_length=125, null=True)),
                ('crystal_name', models.CharField(blank=True, max_length=125, null=True)),
                ('crystal_system', models.CharField(blank=True, max_length=125, null=True)),
                ('cell_length_a', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('cell_length_b', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('cell_length_c', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('cell_angle_alpha', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cell_angle_beta', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cell_angle_gamma', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('space_group_name', models.CharField(blank=True, max_length=125, null=True)),
                ('space_group_it_number', models.IntegerField(blank=True, null=True)),
                ('symmetry_space_group_name_H_M', models.CharField(blank=True, max_length=225, null=True)),
                ('cif_file', models.FileField(upload_to='cif_database')),
                ('file_url', models.URLField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('activate', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
