# Generated by Django 3.1.4 on 2021-01-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrystalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crytal_formula', models.CharField(blank=True, max_length=25, null=True)),
                ('crystal_name', models.CharField(blank=True, max_length=200, null=True)),
                ('crystal_system', models.CharField(max_length=25)),
                ('cell_lenght_a', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('cell_lenght_b', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('cell_lenght_c', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('cell_angle_alpha', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('cell_angle_beta', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('cell_angle_gamma', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
            ],
        ),
    ]
