# Generated by Django 3.1.14 on 2023-08-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_spacing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crystaldata',
            name='symmetry_space_group_name_H_M',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='crystaldata',
            name='crystal_formula',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='crystaldata',
            name='crystal_system',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='crystaldata',
            name='space_group_name',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
