# Generated by Django 3.1.4 on 2021-01-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_spacing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crystaldata',
            old_name='crytal_formula',
            new_name='crystal_formula',
        ),
        migrations.AlterField(
            model_name='crystaldata',
            name='crystal_name',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
