# Generated by Django 3.1.4 on 2021-01-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_spacing', '0002_auto_20210102_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='crystaldata',
            name='cif_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='crystaldata',
            name='cell_angle_alpha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='crystaldata',
            name='cell_angle_beta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='crystaldata',
            name='cell_angle_gamma',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
