# Generated by Django 3.1.4 on 2022-04-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_spacing', '0002_auto_20220403_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='CifUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cif_file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
