# Generated by Django 3.1.14 on 2023-08-22 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('d_spacing', '0002_auto_20230821_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crystaldata',
            old_name='space_group_IT_number',
            new_name='space_group_it_number',
        ),
    ]
