# Generated by Django 3.1.4 on 2022-04-04 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('d_spacing', '0003_cifupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CifUpload',
        ),
    ]
