# Generated by Django 3.1.4 on 2022-04-15 22:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('d_spacing', '0004_delete_cifupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='crystaldata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crystaldata',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='crystaldata',
            name='cif_file',
            field=models.FileField(default=2, upload_to='cif_database'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crystaldata',
            name='crystal_system',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='crystaldata',
            name='space_group_IT_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
