# Generated by Django 3.1.4 on 2022-04-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_spacing', '0005_auto_20220416_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crystaldata',
            name='crystal_system',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
