# Generated by Django 3.1.4 on 2022-04-16 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('d_spacing', '0007_crystaldata_activated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crystaldata',
            old_name='activated',
            new_name='activate',
        ),
    ]
