# Generated by Django 3.1.4 on 2022-04-18 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('d_spacing', '0008_auto_20220416_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crystaldata',
            old_name='timestamp',
            new_name='created',
        ),
    ]
