# Generated by Django 3.1.4 on 2022-05-22 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_myuser_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'Accounts', 'verbose_name_plural': 'Accounts'},
        ),
    ]
